import subprocess

def check_and_manage_dependencies(required_libraries: str) -> str:
    """
    Checks the system for specified Python dependencies and advises on missing ones.

    This tool is used when analyzing code generated by the AI agent to ensure
    all required third-party libraries are available in the virtual environment.

    Args:
        required_libraries (str): A comma-separated string of library names
                                   (e.g., "requests, pandas, pillow").

    Returns:
        str: Message about installation of missing libraries.
    """
    try:
        libraries = [lib.strip() for lib in required_libraries.split(',')]
    except Exception:
        return "Error: Please provide a comma-separated list of libraries."
    missing_libs = []
    print(f"Checking dependency availability for: {', '.join(libraries)}...")

    for lib in libraries:
        try:
            # Use 'pip show' to check if the package is installed.
            # The return code helps determine success/failure robustly.
            result = subprocess.run(
                ['pip', 'show', lib],
                capture_output=True,
                text=True,
                check=True
            )
            if "Version:" in result.stdout:
                 print(f"Found {lib} (Installed version details retrieved).")
            else:
                 # This is a fallback/unexpected state but treats it as success if subprocess didn't error out.
                 print(f"Note: Could not find specific version info for {lib}, but pip executed successfully.")

        except subprocess.CalledProcessError:
            missing_libs.append(lib)
            print(f"Missing dependency detected: {lib}.")
        except FileNotFoundError:
            return "FATAL ERROR: 'pip' command not found. Ensure pip is installed and in your system PATH."

    if missing_libs:
        for lib in missing_libs:
            subprocess.run(
                ['pip', 'install', lib])
        return f"{lib} was installed using pip succesfully"
    else:
        return "\nAll specified dependencies are installed and available.\n"
